import Head from "next/head";
import localFont from "next/font/local";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Cog, LogOut, MessageCircle, User, Users } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { useAuthStore } from "@/store/auth";
import NavBar from "@/components/sections/NavBar";
import PostForm from "@/components/sections/PostForm";
import { useEffect } from "react";
import usePostStore, { Post } from "@/store/posts";
import React from "react";

const geistSans = localFont({
  src: "../styles/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../styles/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavBar />
        <main className="container mx-auto mt-8 grid grid-cols-4 gap-8">
          <aside className="col-span-1">
            <Sidebar />
          </aside>
          <div className="col-span-2 space-y-4">
            <PostForm />
            <PostList />
          </div>
          <aside className="col-span-1 space-y-8">
            <PeopleYouMayKnow />
            <BoostYourPost />
          </aside>
        </main>
      </div>
    </div>
  );
}

const PostList = () => {
  const { posts, loading, submitting, fetchPosts } = usePostStore();
  console.log("Posteos PostList: ", posts);
  useEffect(() => {
    fetchPosts();
  }, [fetchPosts]);
  return (
    <div className="gap-4 flex flex-col">
      {submitting ? <PostCardSkeleton /> : null}
      {loading ? (
        <>
          <PostCardSkeleton />
          <PostCardSkeleton />
          <PostCardSkeleton />
        </>
      ) : (
        posts?.map((data) => <PostCard {...data} key={data.id} />)
      )}
    </div>
  );
};

const PostCardSkeleton = () => {
  return (
    <Card>
      <CardContent className="p-6">
        <div className="flex items-center space-x-4 mb-4">
          {/* Skeleton Avatar */}
          <div className="w-10 h-10 bg-gray-300 rounded-full animate-pulse"></div>
          <div className="flex-1 space-y-2">
            {/* Skeleton Name */}
            <div className="w-24 h-4 bg-gray-300 rounded animate-pulse"></div>
            {/* Skeleton Description */}
            <div className="w-48 h-4 bg-gray-200 rounded animate-pulse"></div>
          </div>
        </div>

        {/* Skeleton Post Content */}
        <div className="space-y-3">
          <div className="w-full h-4 bg-gray-300 rounded animate-pulse"></div>
          <div className="w-5/6 h-4 bg-gray-300 rounded animate-pulse"></div>
          <div className="w-3/4 h-4 bg-gray-300 rounded animate-pulse"></div>
        </div>
      </CardContent>
    </Card>
  );
};

const Sidebar = () => {
  const { logout, user } = useAuthStore();
  return (
    <Card>
      <CardHeader>
        <CardTitle>{user?.username}</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Button variant="ghost" className="w-full justify-start">
          <User className="mr-2 h-4 w-4" />
          Profile
        </Button>
        <Button variant="ghost" className="w-full justify-start">
          <Users className="mr-2 h-4 w-4" />
          Find friends
        </Button>
        <Button variant="ghost" className="w-full justify-start">
          <MessageCircle className="mr-2 h-4 w-4" />
          User analytics
        </Button>
        <Button variant="ghost" className="w-full justify-start">
          <Cog className="mr-2 h-4 w-4" />
          Settings
        </Button>
        <Button variant="ghost" className="w-full justify-start">
          <User className="mr-2 h-4 w-4" />
          Security data
        </Button>
        <Button
          variant="ghost"
          className="w-full justify-start text-red-500"
          onClick={logout}
        >
          <LogOut className="mr-2 h-4 w-4" />
          Log out
        </Button>
      </CardContent>
    </Card>
  );
};

const PostCard = (props: Post) => {
  return (
    <Card>
      <CardContent className="p-6">
        <div className="flex items-center space-x-4 mb-4">
          <Avatar>
            <AvatarImage
              src="/placeholder.svg?height=40&width=40"
              alt="Tony Stark"
            />
            <AvatarFallback>TS</AvatarFallback>
          </Avatar>
          <div>
            <h3 className="font-semibold">{props.userId}</h3>
            <p className="text-sm text-muted-foreground">
              Cognitive Person | Enthusiastic scientist | Worked on 300....
            </p>
          </div>
        </div>
        <p>{props.content}</p>
      </CardContent>
    </Card>
  );
};

const PeopleYouMayKnow = () => {
  return (
    <Card>
      <CardHeader>
        <CardTitle>People you may know</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {[
          "Tony Stark",
          "Bruce Banners",
          "Natasha Ramanoff",
          "Barton Clint",
        ].map((name, index) => (
          <div key={index} className="flex items-center space-x-4">
            <Avatar>
              {/* <AvatarImage
                src={`/placeholder.svg?height=40&width=40&text=${name.charAt(0)}`}
                alt={name}
              /> */}
              <AvatarFallback>
                {name
                  .split(" ")
                  .map((n) => n[0])
                  .join("")}
              </AvatarFallback>
            </Avatar>
            <div>
              <h4 className="font-semibold">{name}</h4>
              <p className="text-sm text-muted-foreground">6M+ Followers</p>
            </div>
          </div>
        ))}
      </CardContent>
    </Card>
  );
};

const BoostYourPost = () => {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Boost your post</CardTitle>
      </CardHeader>
      <CardContent>
        {/* <Image
          src="/placeholder.svg?height=200&width=300"
          alt="Dog"
          className="w-full rounded-md mb-4"
        /> */}
        <p className="text-sm text-muted-foreground">
          @steve_rogers With my lovable dog named Bruno with a smile &...
        </p>
        <div className="flex items-center mt-2">
          <Avatar className="h-6 w-6">
            <AvatarImage src="/placeholder.svg?height=24&width=24" alt="User" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
          <span className="text-sm ml-2">
            & 180 others liked your post &...
          </span>
        </div>
      </CardContent>
    </Card>
  );
};
